export const  FETCH_RESUMES = 'FETCH_RESUMES';
export const  FETCH_ALL_RESUMES = 'FETCH_ALL_RESUMES';
export const  LOADING_RESUMES = 'LOADING_RESUMES';
export const  SUCCESS_RESUMES = 'SUCCESS_RESUMES';
export const  ERROR_RESUMES = 'ERROR_RESUMES';