import eng from '../assets/png/eng.png';
import spain from '../assets/png/spain.png';
import uk from '../assets/png/united-kingdom.png';
import ch from '../assets/png/chinese-flag.png';
import russia from '../assets/png/russia.png';
import portugal from '../assets/png/portugal.png';
import japan from '../assets/png/japan-flag.png';
import german from '../assets/png/german.png';
import france from '../assets/png/france.png';
import uae from '../assets/png/united-arab-emirates.png';
import india from '../assets/png/india.png';


export const languageOptions = [
    { value: 'English', label: 'English', flag:uk },
    { value: 'French', label: 'French', flag:france },
    { value: 'Spanish', label: 'Spanish', flag:spain },
    { value: 'Chinese', label: 'Chinese', flag:ch },
    { value: 'Arabic', label: 'Arabic', flag:uae },
    { value: 'Portuguese', label: 'Portuguese', flag:portugal },
    { value: 'Bengali', label: 'Bengali', flag:india },
    { value: 'Russian', label: 'Russian', flag:russia },
    { value: 'Japanese', label: 'Japanese', flag:japan },
    { value: 'German', label: 'German', flag:german },
    // { value: 'Javanese', label: 'Javanese' },
    // { value: 'Malay', label: 'Malay' },
    // { value: 'Telugu', label: 'Telugu' },
    // { value: 'Vietnamese', label: 'Vietnamese' },
    // { value: 'Korean', label: 'Korean' },
    // { value: 'Marathi', label: 'Marathi' },
    // { value: 'Tamil', label: 'Tamil' },
    // { value: 'Urdu', label: 'Urdu' },
    // { value: 'Turkish', label: 'Turkish' },
    // { value: 'Italian', label: 'Italian' },
    // { value: 'Thai', label: 'Thai' },
    // { value: 'Gujarati', label: 'Gujarati' },
    // { value: 'Jin', label: 'Jin' },
    // { value: 'SouthernMin', label: 'Southern Min' },
    // { value: 'Persian', label: 'Persian' },
    // { value: 'Polish', label: 'Polish' },
    // { value: 'Pashto', label: 'Pashto' },
    // { value: 'Kannada', label: 'Kannada' },
    // { value: 'Xiang', label: 'Xiang' },
    // { value: 'Malayalam', label: 'Malayalam' },
    // { value: 'Sundanese', label: 'Sundanese' },
    // { value: 'Hausa', label: 'Hausa' },
    // { value: 'Odia', label: 'Odia' },
    // { value: 'Burmese', label: 'Burmese' },
    // { value: 'Hakka', label: 'Hakka' },
    // { value: 'Ukrainian', label: 'Ukrainian' },
    // { value: 'Bhojpuri', label: 'Bhojpuri' },
    // { value: 'Tagalog', label: 'Tagalog' },
    // { value: 'Yoruba', label: 'Yoruba' },
    // { value: 'Maithili', label: 'Maithili' },
    // { value: 'Uzbek', label: 'Uzbek' },
    // { value: 'Sindhi', label: 'Sindhi' },
    // { value: 'Amharic', label: 'Amharic' },
    // { value: 'Fula', label: 'Fula' },
    // { value: 'Romanian', label: 'Romanian' },
    // { value: 'Oromo', label: 'Oromo' },
    // { value: 'Igbo', label: 'Igbo' },
    // { value: 'Azerbaijani', label: 'Azerbaijani' },
    // { value: 'Awadhi', label: 'Awadhi' },
    // { value: 'Gan', label: 'Gan' },
    // { value: 'Cebuano', label: 'Cebuano' },
    // { value: 'Dutch', label: 'Dutch' },
    // { value: 'Kurdish', label: 'Kurdish' },
    // { value: 'Serbo-Croatian', label: 'Serbo-Croatian' },
    // { value: 'Malagasy', label: 'Malagasy' },
    // { value: 'Saraiki', label: 'Saraiki' },
    // { value: 'Nepali', label: 'Nepali' },
    // { value: 'Sinhalese', label: 'Sinhalese' },
    // { value: 'Chittagonian', label: 'Chittagonian' },
    // { value: 'Zhuang', label: 'Zhuang' },
    // { value: 'Khmer', label: 'Khmer' },
    // { value: 'Turkmen', label: 'Turkmen' },
    // { value: 'Assamese', label: 'Assamese' },
    // { value: 'Madurese', label: 'Madurese' },
    // { value: 'Somali', label: 'Somali' },
    // { value: 'Marwari', label: 'Marwari' },
    // { value: 'Magahi', label: 'Magahi' },
    // { value: 'Haryanvi', label: 'Haryanvi' },
    // { value: 'Hungarian', label: 'Hungarian' },
    // { value: 'Chhattisgarhi', label: 'Chhattisgarhi' },
    // { value: 'Greek', label: 'Greek' },
    // { value: 'Chewa', label: 'Chewa' },
    // { value: 'Deccan', label: 'Deccan' },
    // { value: 'Akan', label: 'Akan' },
    // { value: 'Kazakh', label: 'Kazakh' },
    // { value: 'NorthernMin', label: 'Northern Min' },
    // { value: 'Sylheti', label: 'Sylheti' },
    // { value: 'Zulu', label: 'Zulu' },
    // { value: 'Czech', label: 'Czech' },
    // { value: 'Kinyarwanda', label: 'Kinyarwanda' },
    // { value: 'Dhundhari', label: 'Dhundhari' },
    // { value: 'HaitianCreole', label: 'Haitian Creole' },
    // { value: 'EasternMin', label: 'Eastern Min' },
    // { value: 'Ilocano', label: 'Ilocano' },
    // { value: 'Quechua', label: 'Quechua' },
    // { value: 'Kirundi', label: 'Kirundi' },
    // { value: 'Swedish', label: 'Swedish' },
    // { value: 'Hmong', label: 'Hmong' },
    // { value: 'Shona', label: 'Shona' },
    // { value: 'Uyghur', label: 'Uyghur' },
];